version: 0.0
os: linux
files:
  - source: /
    destination: /var/backend/
hooks:
  BeforeInstall:
    - location: BackEnd/scripts/install-dependencies.sh
      runas: root
      timeout: 600
  AfterInstall:
    - location: BackEnd/scripts/npm-install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: BackEnd/scripts/npm-start.sh
      timeout: 300
      runas: root
